import type { Metadata } from 'next';
import {
  coinbaseSans,
  coinbaseText,
  coinbaseMono,
  coinbaseDisplay,
  inter,
} from './font';
import clsx from 'clsx';
import '@/globals.css';
import Providers from '@/providers/providers';
import { Box } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={clsx(
            coinbaseSans.variable,
            coinbaseText.variable,
            coinbaseMono.variable,
            coinbaseDisplay.variable,
            inter.variable
          )}
        >
          <Box
            style={{
              margin: '0 auto',
            }}
            maxWidth={390}
          >
            {children}
          </Box>
        </body>
      </Providers>
    </html>
  );
}
